services:
  app:
    build:
      context: .
    container_name: likemovies-api
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:16.4-alpine3.20
    container_name: postgres-server
    ports:
      - ${DB_PORT}:5432
    volumes:
      - database:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}

volumes:
  database:
    driver: local